name: katarl2
channels:
  - conda-forge
dependencies:
  - python=3.11.13
  - pytorch=2.7.1
  - pip:
      - gymnasium==1.2.0
      - tyro==0.9.28
      - tensorboard==2.20.0
      - matplotlib==3.10.5
